- .gitignore
- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/config/env.rs
- src/config/mod.rs
- src/main.rs
- src/subprocess.rs
Really a first pass... 
Two major questions remain:
1. How to test beyond a valid environment -- assume we need a mock of things
2. Multiple arguments for --set and --remove in conjunction with <argument|command> sub-command
> Initial pass at 'cloudtruth run' command

- src/main.rs
Although this is a large looking change, there are no logic changes here. For each CLI sub-command, I created a function to process the command. I moved the code to handle it out of main, and into the function.
In several cases, I pass in the Templates/Environment/Projects/Parameters objects to the functions. Eventually, I would like to be able to pass in mocks of these for testing purposes.
> Refactor main() into per sub-command functions

- graphql/parameter_queries.graphql
- src/graphql.rs
- src/main.rs
- src/parameters.rs
- src/subprocess.rs
This is a draft, since it does not compile!
In addition to the query changes, I will need to update the upsert for adding parameters.
In most of the errors, I get complaints about `.parameters` is an unknown field in the query.
> Update parameter queries with project filters

- .github/workflows/release.yml
- CHANGELOG.md
- Cargo.rpm.toml
- README.md
Found a good way to do this with a pure rust implementation.
> add a rpm build target for the CLI

- install.sh
Tested in https://github.com/cloudtruth/cloudtruth-cli/actions/runs/823185265
> Make install script more accepting of different tag name formats

- src/environments.rs
- src/graphql.rs
- src/main.rs
- src/parameters.rs
- src/projects.rs
- src/templates.rs
1. Create/use common string for no organization found
2. Rename 'get_id_details()' to 'get_details_by_name()'
> Minor code cleanup

- src/cli.rs
- src/main.rs
- tests/help.txt
- tests/pytest/test_parameters.py
```
(Ricks-MacBook-Pro):~/cloudtruth-cli $ cargo run -q -- param ls -v
+---------------+-------------------------------------------------------------------------------------+---------+---------+--------+--------------------------------------------+
| Name          | Value                                                                               | Source  | Type    | Secret | Description                                |
+---------------+-------------------------------------------------------------------------------------+---------+---------+--------+--------------------------------------------+
| ANOTHER       | VALUE                                                                               | default | static  | false  |                                            | …
```
> Add --dynamic option to 'param ls'

- .dockerignore
- .gitignore
- Makefile
- openapi.yml
This is enough just to get started with the REST API spec being generated by the server.
* It is not hooked into the build.
> [ch4218] initial openapi client generation for rust

- tests/pytest/test_args.py
Passed against staging (after your changes merged), although I expect the CI will fail because it runs against production.
> Add integration test for authentication errors

- tests/pytest/live_test.py
- tests/pytest/test_integrations.py
Finally, added ability to filter to just a single test case to the live_test.py
> Add integration tests that use real FQN/JMES-path

- src/cli.rs
- src/main.rs
- tests/help.txt
- tests/pytest/test_args.py
Added a couple more "general" aliases:
delete: add 'd'
list: add 'l'
Updated config:
Renamed config to configuration
Added alias for 'conf'
For 'current', added 'curr' and 'cur'
> Improve naming and aliases

- src/cli.rs
- src/database/parameters.rs
- src/environments.rs
- src/main.rs
- src/parameters.rs
- src/projects.rs
- src/templates.rs
- tests/help.txt
- tests/pytest/test_parameters.py
- tests/pytest/testcase.py
Also added a default value to 'user_confirm()', so the user can just hit return.
> Add confirmation to 'param del'

- client/src/apis/projects_api.rs
- client/src/models/audit_trail_summary.rs
- client/src/models/patched_value.rs
- client/src/models/value.rs
- openapi.yml
- src/database/parameters.rs
- src/parameters.rs
- src/run.rs
1. Do not fetch values unnecessarily
2. Use 'environment_name' when getting parameter values
> Leverage API updates

- src/main.rs
Added mm/dd/yyyy and mm-dd-yyyy.
> Add more acceptable date formats to --as-of values

- src/cli.rs
- src/database/history.rs
- src/database/mod.rs
- src/database/templates.rs
- src/templates.rs
- tests/help.txt
- tests/pytest/test_templates.py
Also added --show-times option to 'template list'.
Sample output:
```
(Ricks-MacBook-Pro):~/cloudtruth-cli $ target/debug/cloudtruth temp -h
cloudtruth-templates 
Work with CloudTruth templates
USAGE:
cloudtruth templates [SUBCOMMAND]
FLAGS:
SUBCOMMANDS:
delete     Delete the CloudTruth template [aliases: del, d]
edit       Edit the specified template
get        Get an evaluated template from CloudTruth
help       Prints this message or the help of the given subcommand(s)
history    Display template history [aliases: hist, h]
list       List CloudTruth templates [aliases: ls, l]
preview    Evaluate the provided template without storing [aliases: prev, pre]
set        Set the CloudTruth template …
```
> Add 'template history' command

- client/src/models/aws_pull_task_step.rs
- client/src/models/aws_push_task_step.rs
- client/src/models/patched_service_account.rs
- client/src/models/service_account.rs
- client/src/models/service_account_create_response.rs
- openapi.json
- openapi.yml
- patch_client.py
1. Optional ServiceAccount.last_used_at
2. Optional operation enum in push/pull task steps
> Update to latest API changes

- client/src/apis/projects_api.rs
- client/src/models/object_type_enum.rs
- openapi.json
- openapi.yml
- src/audit_logs.rs
- src/database/mod.rs
- src/database/parameter_error.rs
- src/database/parameters.rs
- src/database/templates.rs
- tests/pytest/test_audit_log.py
1. Improve parameter export 422 handling
2. Update audit log types
3. Template preview includes [unused] template-id parameter
> Update to latest API specification

- src/cli.rs
- src/parameters.rs
- tests/help.txt
- tests/pytest/test_parameters.py
Here's a sample output:
```
ct param drift -v
+----------------------------------+------------+-----------------------------------+-----------------------------------------------------+
| Name                             | Difference | CloudTruth                        | Shell                                               |
+----------------------------------+------------+-----------------------------------+-----------------------------------------------------+
| __CF_USER_TEXT_ENCODING          | added      |                                   | 0x1F5:0x0:0x0                                       |
| __CFBundleIdentifier             | added      |                                   | com.apple.Terminal                                  |
| another-param                    | removed    | - …
```
> Add 'parameter drift' command

- .github/workflows/staging.yml
@amason should I disable on other builds too?
> [sc-8825] disable backup testing on staging builds

- .github/workflows/create-draft-release.yml
- .github/workflows/production.yml
Still outstanding action are:
actions-rs/toolchain@v1
actions/create-release
> [sc-9268] cloudtruth-cli-workflow-updates-part-2

- DEVELOPMENT.md
- src/installation/install.rs
- src/installation/install_errors.rs
added instructions for Windows builds on Linux/Mac as well as updates to other sections
> fix Windows build warnings and update DEVELOPMENT.md

- .github/workflows/ci.yml
- .github/workflows/nightly.yaml
- .github/workflows/production.yml
- .github/workflows/staging.yml
- integration-tests/test_audit_log.py
- integration-tests/test_backup.py
- integration-tests/test_parameters.py
> skip known issues that are breaking tests (re-enable after next release)

- ci/src/cli/generate_dockerfiles.rs
- ci/src/cli/generate_help_text.rs
- ci/src/templates/docker_template.rs
- ci/src/templates/help_text_template.rs
Not really needed, but I'm getting a feel for concurrent rust for later improvements
> CI script: concurrency improvements for blocking IO

- tests/test_templates.rs
* environment evaluation
* --as-of for timestamp and tags
> Template Integration Tests

- integration-tests/cleanup.py
Couple of things to help with nightly cleanups. The big thing is waiting between deletes so projects can get properly trimmed.
> sc-11564 add --profile and sleep between deletes in case of large project deletes

- .github/workflows/ci.yml
- .github/workflows/test-nightly.yml
Story details: https://app.shortcut.com/cloudtruthunified/story/12629
> chore: [sc-12629] [CLI] Make Test-Nightly run OS tests sequentially
