src/graphql.rs
src/macros.rs
src/main.rs
src/parameters.rs

A parameter can exist in CloudTruth without an explicitly configured value. I.e., there is a difference between a parameter without a value set and a parameter with an empty value. The CLI client had been incorrectly treating the former case as a missing parameter. Now the states are properly accounted for.

Fix an issue where a parameter without a set value was being reported as not existing.

---

src/graphql.rs

A recent change to the Rust toolchain causes clippy to complain about the capitalization. The change just tells clippy to ignore these changes.

Ignore clippy issue with GraphQL capitialization in types

---

src/main.rs
src/parameters.rs
src/subprocess.rs

The 'run' command displayed startup delay when we had many parameters present. It looks like the initial query had all the data, but we previously queried the parameters individually.

Get all environment parameter values in one query

---

src/cli.rs
src/main.rs
src/subprocess.rs

Replace CLI run "--preserve" flag with "--inherit <none|underlay|overlay|exclusive>" for more environment control.
```
new-host-4):~/cloudtruth-cli $ cargo run -q -- run -h
cloudtruth-run 
Run a shell with the parameters in place
USAGE:
cloudtruth run [OPTIONS] [-- <arguments>...]
FLAGS:
OPTIONS:
-c, --command <command>        Run this command
-i, --inherit <inheritance>    Handle the relationship between local and CloudTruth environments. [default: overlay]
[possible values: none, underlay, overlay, exclusive]
-r, --remove <remove>...       Remove the variables from the CloudTruth environment for this run
-s, --set <set>...             Set the variables in this run, even possibly …
```

Introduce CLI run inherit option

---

src/config/env.rs
src/config/mod.rs
src/main.rs

When the "old" environment variable is in use, a different error message is displayed to the user telling them to update to the new environment variable.
```
(new-host-4):~/cloudtruth-cli $ cargo run -q -- env ls
default
my_new_environment
(new-host-4):~/cloudtruth-cli $ unset CLOUDTRUTH_API_KEY
(new-host-4):~/cloudtruth-cli $ cargo run -q -- env ls
Pleaes use CLOUDTRUTH_API_KEY to set the API key instead of CT_API_KEY
default
my_new_environment
(new-host-4):~/cloudtruth-cli $ 
```

Change CT_ to CLOUDTRUTH_ for app environment variables

---

Cargo.lock
Cargo.toml
graphql/parameter_queries.graphql
src/cli.rs
src/main.rs
src/parameters.rs

I specifically did not add a `--secrets` option to display the secrets, but that would be quite simple.
Here's a sample output (with no secrets):
```
(new-host-4):~/cloudtruth-cli $ cargo run -q -- param -h
cloudtruth-parameters 
Work with CloudTruth parameters
USAGE:
cloudtruth parameters [SUBCOMMAND]
FLAGS:
SUBCOMMANDS:
get     Gets value for parameter in the selected environment
help    Prints this message or the help of the given subcommand(s)
list    List CloudTruth parameters [aliases: ls]
set     Set a static value in the selected environment for an existing parameter or creates a new one if needed
(new-host-4):~/cloudtruth-cli $ cargo run -q -- param list -h
cloudtruth-parameters-list 
List …
```

Add parameters 'list --values' option

---

CHANGELOG.md
README.md
graphql/project_queries.graphql
graphql/schema.graphql
src/cli.rs
src/config/mod.rs
src/main.rs
src/projects.rs
src/subprocess.rs

1. Updated to latest GraphQL schema (mainly to query project by name)
2. Add basic project queries, and CLI command to view list of projects
3. Refactor stderr output for reuse
4. Add --project argument to CLI, and validate it
Here's some sample output:
```
(new-host-4):~/cloudtruth-cli $ cargo run -q -- -e foo param ls
The 'foo' environment could not be found in your account.
(new-host-4):~/cloudtruth-cli $ cargo run -q -- -e foo --project prj param ls
The 'foo' environment could not be found in your account.
The 'prj' project could not be found in your account.
(new-host-4):~/cloudtruth-cli $ echo $?
2
(new-host-4):~/cloudtruth-cli $ cargo run -q -- proj ls
Proj2
Project1
default
(new-host-4):~/cloudtruth-cli $ 
```
The above "could not be found in your account" messages are in red on …

Initial Projects additions

---

src/cli.rs
src/config/file.rs
src/config/mod.rs
src/main.rs

Without this change, we need to look at the config file (usually getting into the editor via `config edit`) to see what profiles we have configured.

Add 'config list' option

---

src/environments.rs
src/main.rs
src/projects.rs
src/subprocess.rs

Instead of checking that environment/project are valid (and then tossing those ID's), we remember the IDs for later use. This simplifies some of the other places where we previously needed to resolve the environment ID. This should avoid at least one query (and probably two) to the CloudTruth servers.
With the new validation, I shuffled some things around to avoid validating environment/project before necessary. For example, there is no need to make sure a valid project is specified when getting a list of projects.

Change how project/environment are validated/resolved

---

src/main.rs

Without this, we could get validation errors even though we should not need to validate the project/environment.
```
(new-host-4):~/cloudtruth-cli $ cargo run -q -- -e foo --project bar env ls 
Environment1
default
The 'foo' environment could not be found in your account.
The 'bar' project could not be found in your account.
(new-host-4):~/cloudtruth-cli $
```

Avoid environment/project validation errors for those sub-commands

---

CHANGELOG.md
graphql/parameter_queries.graphql
src/cli.rs
src/main.rs
src/parameters.rs

```
(new-host-4):~/cloudtruth-cli $ cargo run -q -- --project Project1 param ls -v
+---------------+-------------+---------+-------------+
| Name          | Value       | Source  | Description |
+---------------+-------------+---------+-------------+
| FOO           | bar         | default |             |
| PRJ1_FROM_CLI | crazy-value | default |             |
| SNA           | foo         | default |             |
+---------------+-------------+---------+-------------+
(new-host-4):~/cloudtruth-cli $ cargo run -q -- param ls -v
+---------------+---------------+---------+---------------------------------+
| Name          | Value         | Source  | Description                     |
+---------------+---------------+---------+---------------------------------+
| …
```

Add ability to delete a parameter from the specified project/environment

---

graphql/environment_queries.graphql
graphql/project_queries.graphql
graphql/template_queries.graphql
src/cli.rs
src/environments.rs
src/main.rs
src/projects.rs
src/templates.rs

```
(new-host-4):~/cloudtruth-cli $ cargo run -q -- proj ls 
Proj2
Project1
default
(new-host-4):~/cloudtruth-cli $ cargo run -q -- proj ls -v
+----------+-------------------------------------+
| Name     | Description                         |
+----------+-------------------------------------+
| Proj2    | Just another project                |
| Project1 | My very first project!              |
| default  | The auto-generated default project. |
+----------+-------------------------------------+
(new-host-4):~/cloudtruth-cli $ cargo run -q -- proj ls -v -f csv
Name,Description
Proj2,Just another project
Project1,My very first project!
default,The auto-generated default project.
(new-host-4):~/cloudtruth-cli $ 
(new-host-4):~/cloudtruth-cli $ cargo run -q -- env ls …
```

Add --values/--format options to projects/environments list sub-command

---

src/cli.rs
src/main.rs

```
(new-host-4):~/cloudtruth-cli $ cargo run -q -- param ls -v
+-----------------+---------------+---------+---------------------------------+
| Name            | Value         | Source  | Description                     |
+-----------------+---------------+---------+---------------------------------+
| ANOTHER_VALUE   | uninteresting | default | set just description            |
| MY_KEY_NAME     | my_value      | default | dummy key name/value            |
| MY_SECRET       | *****         | default | something to test secret hiding |
| new_param_value | third value   | default | fresh description               |
+-----------------+---------------+---------+---------------------------------+
(new-host-4):~/cloudtruth-cli $ cargo run -q -- param ls -v -s …
```

Add --secrets to 'param list' to show the secret values

---

graphql/template_queries.graphql
src/main.rs
src/templates.rs

Sample output:
```
(new-host-4):~/cloudtruth-cli $ cargo run -q -- templates ls -v
+---------------+------------------+
| Name          | Description      |
+---------------+------------------+
| some template | some description |
+---------------+------------------+
(new-host-4):~/cloudtruth-cli $ cargo run -q -- --project Project1 templates ls 
There are no templates in project `Project1`.
(new-host-4):~/cloudtruth-cli $
```

Consider project in most 'template' queries

---

graphql/project_queries.graphql
src/cli.rs
src/graphql.rs
src/main.rs
src/projects.rs

```
(Ricks-MacBook-Pro):~/cloudtruth-cli2 $ cargo run -q -- proj ls -v 
+----------+-------------------------------------+
| Name     | Description                         |
+----------+-------------------------------------+
| Proj2    | Just another project                |
| Project1 | My very first project!              |
| default  | The auto-generated default project. |
+----------+-------------------------------------+
(Ricks-MacBook-Pro):~/cloudtruth-cli2 $ cargo run -q -- proj set -h
cloudtruth-projects-set 
Create/update a CloudTruth project
USAGE:
cloudtruth projects set [OPTIONS] <NAME>
FLAGS:
OPTIONS:
-d, --desc <description>    Project's description
ARGS:
<NAME>    Project …
```

Add 'projects' management functions -- 'set' and 'delete'

---

src/main.rs
src/parameters.rs

This is intended to reduce the code, and does not impact user functionality.
This uses the Parameters::get_parameter_details() interface to produce a list of name for the CLI. With these changes, it follows a similar pattern to the `list` subcommand for environments and project -- fetch the details, and display the names unless given the `--values` flag.

Remove 'get_parameter_names()' Parameters interface

---

src/main.rs

All updates are to cleanup main.rs. 
1. Pass `SubProcessIntf` into `process_run_command()` to enable future testing
2. Add document strings on many functions
3. Make `process_xxx_command()` argument ordering consistent
4. Add `org_id` into `ResolvedIds` to reduce number of args necessary

Minor code cleanup

---

.dockerignore
Dockerfile.dev
Makefile

I found this useful so I did not have to figure out what my linux host needed to be installed to build the cli.
It does not provide a CLI runtime environment image, it is purely for development.
$ make image
$ make shell
(inside container)
cargo build

a clean docker environment for building the CLI

---

.github/workflows/ci.yml
tests/pytest/live_test.py
tests/pytest/test_args.py
tests/pytest/test_environments.py
tests/pytest/test_parameters.py
tests/pytest/test_projects.py
tests/pytest/test_run.py
tests/pytest/testcase.py

Here are some supporting items:
1. Added optional job-id suffix to project and environment names to support simultaneous runs
2. Track and automatically cleanup projects and environments
3. Windows adjustments: double quotes, line endings, output decoding, printenv/set

Run integration test in CI

---

src/cli.rs
src/config/env.rs
src/config/mod.rs
src/main.rs

Here's a sample output:
```
(new-host-4):~/cloudtruth-cli $ env | grep CLOUDTRUTH
CLOUDTRUTH_PROFILE=stage
(new-host-4):~/cloudtruth-cli $ cargo run -q -- config ls -v
+---------+-------+-------------+----------+----------------------------------------+
| Name    | API   | Environment | Project  | Description                            |
+---------+-------+-------------+----------+----------------------------------------+
| ci-rw   | ***** |             |          | CI account to read/write to production |
| ct-ops  | ***** |             |          |                                        |
| ci      | ***** |             |          | CI account on production server        |
| default | ***** |             |          |                                        |
| stage   | ***** | …
```

Allow user to select profile using CLOUDTRUTH_PROFILE in environment

---

src/main.rs
tests/pytest/test_args.py
tests/pytest/test_environments.py
tests/pytest/test_parameters.py
tests/pytest/test_projects.py
tests/pytest/testcase.py

1. CLI now fails when attempting to change parent of existing environment
2. Add test for environment inheritance
3. Add test to verify each environment can have different parameter values

Improve environment testing and code

---

Makefile
tests/Makefile
tests/cli_walk.py
tests/help.txt
tests/pytest/testcase.py

The cli_walk.py walks the entire CLI tree (based on output format) and prints the help. The `cli_walk.py check` fails if anything has changed in the cli.  This will be useful when trying to see differences between 2 versions.

Add 'quick' check to make sure CLI is not unintentionally changing

---

.github/workflows/create-draft-release.yml

Make sure the Cargo.toml version agrees with the tag version. Without these changes, some of the assets do not have the right name, so the draft-release will fail during download.

Check the release tag contains the cargo version

---

graphql/integration_queries.graphql
src/cli.rs
src/integrations.rs
src/main.rs
tests/help.txt
tests/pytest/test_args.py

Sample output (with single integration):
```
(new-host-4):~/cloudtruth-cli $ cargo run -q -- integrations -h
cloudtruth-integrations 
Work with CloudTruth integrations
USAGE:
cloudtruth integrations [SUBCOMMAND]
FLAGS:
SUBCOMMANDS:
help    Prints this message or the help of the given subcommand(s)
list    List CloudTruth integrations [aliases: ls]
(new-host-4):~/cloudtruth-cli $ cargo run -q -- integrations list -h
cloudtruth-integrations-list 
List CloudTruth integrations
USAGE:
cloudtruth integrations list [FLAGS] [OPTIONS]
FLAGS:
-v, --values     Display integration information/values
OPTIONS:
-f, --format <format> …
```

Add ability to view integrations

---

graphql/integration_queries.graphql
src/cli.rs
src/graphql.rs
src/integrations.rs
src/main.rs
tests/help.txt

Cherry-picked commit from other branch. Could not figure out how to get rebase/merge conflicts resolved.
```
(new-host-4):~/cloudtruth-cli $ cargo run -q -- integrations -h
cloudtruth-integrations 
Work with CloudTruth integrations
USAGE:
cloudtruth integrations [SUBCOMMAND]
FLAGS:
SUBCOMMANDS:
delete    Delete specified CloudTruth integration [aliases: del]
help      Prints this message or the help of the given subcommand(s)
list      List CloudTruth integrations [aliases: ls]
(new-host-4):~/cloudtruth-cli $ cargo run -q -- integrations ls -v
+-------------+--------+---------------------+
| Name        | Type   | FQN                 |
+-------------+--------+---------------------+
| Rick …
```

Add 'integrations delete' capability for AWS and GitHub

---

Cargo.lock
Cargo.toml
graphql/integration_queries.graphql
src/cli.rs
src/integrations.rs
src/main.rs
tests/help.txt

```
(new-host-4):~/cloudtruth-cli $ cargo run -q -- int ls -v
+-------------+--------+---------------------+
| Name        | Type   | FQN                 |
+-------------+--------+---------------------+
| Rick Porter | Github | GitHub::Rick Porter |
+-------------+--------+---------------------+
(new-host-4):~/cloudtruth-cli $ cargo run -q -- int -h
cloudtruth-integrations 
Work with CloudTruth integrations
USAGE:
cloudtruth integrations [SUBCOMMAND]
FLAGS:
SUBCOMMANDS:
delete     Delete specified CloudTruth integration [aliases: del]
explore    Explore specific integration options [aliases: exp, ex, e]
help       Prints this message or the help of the given subcommand(s)
list       List …
```

Add 'integrations explore' to query integrations for FQNs

---

Makefile
src/cli.rs
src/main.rs
tests/help.txt

The `-y/--yes` are now visible, but the `--confirm` still works too (although undocumented).
Also use common names for some CLI constants that should have been shared long ago.

Prefer -y/--yes to --confirm

---

graphql/integration_queries.graphql
src/cli.rs
src/graphql.rs
src/integrations.rs
src/main.rs
tests/help.txt

Creating integrations requires much "venue" specific code, and sometimes visiting websites for that venue. So, we're not going to implement the `integrations create`. To keep things symmetric, this removes the `integrations delete` from the CLI.

Remove 'integrations delete' code

---

tests/pytest/live_test.py
tests/pytest/test_args.py
tests/pytest/test_parameters.py
tests/pytest/test_run.py
tests/pytest/testcase.py

First commit is for improved secret handing in `param export`.
Second commit was to allow me to run against staging by using CLOUDTRUTH_PROFILE environment variable.

Test updates for 'param export', and CT_PROFILE

---

graphql/template_queries.graphql
src/cli.rs
src/main.rs
src/templates.rs
tests/help.txt

When server started requiring templates to have a `showSecret` flag to display the secrets, the CLI was not updated.

Add --secrets option to templates

---

graphql/parameter_queries.graphql
graphql/schema.graphql
src/cli.rs
src/main.rs
src/parameters.rs
tests/help.txt
tests/pytest/test_parameters.py

Sample output:
```
(new-host-4):~/cloudtruth-cli $ cargo run -q -- int ls -v
+-------------+--------+---------------------+
| Name        | Type   | FQN                 |
+-------------+--------+---------------------+
| Rick Porter | Github | GitHub::Rick Porter |
+-------------+--------+---------------------+
(new-host-4):~/cloudtruth-cli $ cargo run -q -- int ex "Rick Porter" repositories -v
+------------------------------------+--------------------------------------------------------------------------------+
| Name                               | FQN                                                                            |
+------------------------------------+--------------------------------------------------------------------------------+
| repositories                       | …
```

Allow setting dynamic parameters from the CLI

---

Cargo.lock
Cargo.toml
src/main.rs
src/table.rs

This reduces the amount that `main.rs` needs to know about table formatting, and avoids formatting issues.
This also lays the groundwork for adding more format types with less code change. :)

Encapsulate table formatting in new module

---

src/main.rs

I unsuccessfully tried to simplify the code (only filling in the default project/environment in the `resolve_ids()` function, but that yielded some strange results in the integration tests that I did not feel like chasing down.
I also looked for other cases where this might be an issue, and could not find any.

Fix issue with empty default project

---

client/docs/ProjectsApi.md
client/src/apis/projects_api.rs
openapi.yml
patch_client.py
tests/pytest/test_parameters.py

This aligns the OpenApi spec with what is returned by `projects_parameters_destroy()`
Updated the client patch to not update the destroy method with the code to `remove_null_values()` call.
Updated testing to check the output on delete for both normal and secret parameters.

Fix 'param del' failure message

---

src/config/env.rs
src/config/mod.rs
src/main.rs

This deprecates the old option, and the user must use the CLOUDTRUTH_API_KEY to set the API key via an environment variable.

Deprecate support for CT_API_KEY

---

src/cli.rs
src/config/file.rs
src/config/mod.rs
src/config/profiles.rs
src/main.rs
tests/help.txt
tests/pytest/test_args.py
tests/pytest/testcase.py

Example outputs:
```
(new-host-3):~/cloudtruth-cli $ target/debug/cloudtruth config current 
+-------------+----------------+-----------------+
| Parameter   | Value          | Source          |
+-------------+----------------+-----------------+
| Profile     | local          | shell           |
| API key     | ********       | profile (local) |
| Project     | MyFirstProject | profile (local) |
| Environment | default        | default         |
+-------------+----------------+-----------------+
(new-host-3):~/cloudtruth-cli $ target/debug/cloudtruth --profile stage config current -x
+-----------------+------------------------------------+-----------------+
| Parameter       | Value                              | Source          | …
```

Add 'config current' to show where CLI parameters are coming from

---

Makefile
client/src/apis/api_api.rs
client/src/apis/audit_api.rs
client/src/apis/configuration.rs
client/src/apis/environments_api.rs
client/src/apis/integrations_api.rs
client/src/apis/invitations_api.rs
client/src/apis/memberships_api.rs
client/src/apis/organizations_api.rs
client/src/apis/projects_api.rs
client/src/apis/serviceaccounts_api.rs
client/src/apis/users_api.rs
patch_client.py
src/environments.rs
src/integrations.rs
src/main.rs
src/openapi.rs
src/parameters.rs
src/projects.rs
src/templates.rs

Code generation changes:
* Added cookie to generated `OpenApiConfig` (really `crate::openapi::configuration::Configuration`)
* Added code to add `cookie` header if it is in the OpenApiConfig
* Added code to cache the cookie from the `set-cookie` header, if was not already populated
There did not appear to be a good way to make `open_api_config()` return a mutable reference (in part due to lifetime issues), so the `OpenApiConfig` is now part of `main()` and passed into all the places that use it.

Add cookies to API requests

---

CHANGELOG.md
Cargo.lock
Cargo.toml
tests/help.txt

* Pickup latest OpenAPI changes.
* Add HTTP Cookie header sent from the first response in subsequent requests.
* Remove generated client docs from repository.
* Restore GiHub CI testing.

1.0.1 release

---

Cargo.lock
src/table.rs

Made one adjustment since the YAML package now includes a trailing newline.

Regenerate the Cargo.lock to pick up new crate versions

---

src/main.rs
src/parameters.rs
tests/pytest/test_parameters.py

When a new parameter is added and we fail to add the value (e.g. bad FQN), remove the parameter.

Cleanup new parameters when fail to add value

---

client/src/apis/api_api.rs
client/src/apis/audit_api.rs
client/src/apis/configuration.rs
client/src/apis/environments_api.rs
client/src/apis/integrations_api.rs
client/src/apis/invitations_api.rs
client/src/apis/memberships_api.rs
client/src/apis/organizations_api.rs
client/src/apis/projects_api.rs
client/src/apis/serviceaccounts_api.rs
client/src/apis/users_api.rs
patch_client.py
src/config/env.rs
src/config/file.rs
src/config/mod.rs
src/config/profiles.rs
src/main.rs
src/openapi.rs
src/parameters.rs
tests/pytest/test_environments.py
tests/pytest/test_timing.py
tests/pytest/testcase.py

1. When getting a single Parameter, mask_secrets unless the value is needed.
2. Add configurable REST_DEBUG to see URLs and timing info
3. Use a 2-step 'get_details_by_name()' -- get the id, then get the value by id (workaround for server issue)

Performance improvements

---

client/README.md
client/src/apis/integrations_api.rs
client/src/apis/projects_api.rs
client/src/models/patched_value.rs
client/src/models/value.rs
openapi.yml
src/main.rs
src/parameters.rs
src/subprocess.rs

Here's an example (without the benefit of color) of a parameter list when there's a broken integration:
```
(Ricks-MacBook-Pro):~/cloudtruth-cli $ target/debug/cloudtruth param ls -v
+--------------+-------+---------+---------+--------+-------------+
| Name         | Value | Source  | Type    | Secret | Description |
+--------------+-------+---------+---------+--------+-------------+
| my_dyn_param |       | default | dynamic | false  |             |
+--------------+-------+---------+---------+--------+-------------+
Errors resolving parameters:
my_dyn_param: No integration available for `github://rickporter-tuono/cloudtruth_test/main/short.yaml`.
(Ricks-MacBook-Pro):~/cloudtruth-cli $ 
```

Adjustments for dynamic error handling changes

---

CHANGELOG.md
Cargo.lock
Cargo.toml
tests/help.txt

* Added `parameters difference` command to compare parameters between two different environments.
* Performance improvements:
* Reduce the number of instances where secrets are retrieved.
* Get parameter details using retrieve (by identifier), instead of a filtered list.
* Added REST profiling prints when `CLOUDTRUTH_REST_DEBUG` is true.
* Improved feedback for errors retrieving dynamic parameters.
* Use standard cookie handling.

1.0.3 release

---

src/database/parameters.rs
tests/pytest/test_timing.py

Removes a server workaround. Back to resolving the parameter by a filtered list with secrets resolved -- one fewer step than workaround.

Use filtered parameter list to get individual parameters

---

src/cli.rs
src/database/templates.rs
src/templates.rs
tests/help.txt
tests/pytest/test_templates.py

Sample output:
```
(Ricks-MacBook-Pro):~/cloudtruth-cli2 $ target/debug/cloudtruth template get my_temp 
param1 = foo
param2 = some value
param3 = *****
p2 = some value
(Ricks-MacBook-Pro):~/cloudtruth-cli2 $ target/debug/cloudtruth template get my_temp -r
param1 = {{ param1 }}
param2 = {{ param2 }}
param3 = {{ secret1 }}
p2 = {{ param2 }}
(Ricks-MacBook-Pro):~/cloudtruth-cli2 $ target/debug/cloudtruth template get --raw my_temp
param1 = {{ param1 }}
param2 = {{ param2 }}
param3 = {{ secret1 }}
p2 = {{ param2 }}
(Ricks-MacBook-Pro):~/cloudtruth-cli2 $ 
```

Add '--raw' option to 'template get'

---

src/cli.rs
tests/help.txt

Using the 'long_about' caused the entire help to get re-formatted to a long form on Windows. The shorter help with exposing the '--no-' flags seems a reasonable solution.

Improve 'parameters set' help

---

CHANGELOG.md
Cargo.lock
Cargo.toml
tests/help.txt

* Updated `parameters set` with type and rule arguments:
* Added `--type <string|integer|bool>` for parameter type.
* Added `--max`, `--min`, `--max-len`, `--min-len`, `--regex` to set the rules, and a `no` 
version of each (e.g. `--no-min-len`) to delete the rules.
* Updated `parameters list` with type and rule information:
* Added "Param Type" and "Rules" (count) to the `--values` output.
* Added `--rules` view of existing rules.

1.0.6 release

---

src/parameters.rs

There was a regression in 1.0.6 when parameter values were no longer retrieved for `param list --dynamic`... The Values are needed to get FQN/JMES-path information.

Get parameter values so that FQN and JMES-path are available

---

CHANGELOG.md
Cargo.lock
Cargo.toml
tests/help.txt

* Improved `templates` commands:
* Added `history` command.
* Better error feedback when `get` or `preview` fail due to external parameters.
* Added `--as-of` argument to `preview`.
* Added `--show-times` flag to `list`.
* Added `--as-of` argument to `parameter export`.
* Support additional date formats in `--as-of` arguments (e.g. `mm/dd/YYYY`, `mm-dd-YYYY`). 
* Improved integration tests to use environment variables.

1.0.7 release

---

tests/pytest/test_integrations.py
tests/pytest/test_parameters.py
tests/pytest/test_run.py
tests/pytest/test_templates.py
tests/pytest/test_timing.py
tests/pytest/testcase.py

A couple of the re-ordering/refactoring things were done to support a search for uncheck values:
```
grep -nA 1 "result = " tests/pytest/*.py | grep -v "result = " | grep -v "assertResult"
```

Fix a couple missed instances of no success checking

---

CHANGELOG.md
Cargo.lock
Cargo.toml
tests/help.txt

* Added `environments tag` command with the following sub-commands:
* `list` - display tags for a specific environment.
* `set` - create/update environment tag properties.
* `delete` - delete environment tag.
* Added `--show-times` to `list` for `integrations`, `projects`, and `environments`.
* Changed parameter properties `dynamic` to `external`, and `static` to `internal`.
* Added Centos-8 RPM support.
* Improved debugging for failed tests.

1.0.8 release

---

src/cli.rs
src/templates.rs
tests/help.txt
tests/pytest/test_integrations.py
tests/pytest/test_templates.py

Here's the help:
validate    Validate a CloudTruth template [aliases: valid, val, v]
```
(Ricks-MacBook-Pro):~/cloudtruth-cli $ target/debug/cloudtruth t v -h
cloudtruth-templates-validate 
Validate a CloudTruth template
USAGE:
cloudtruth templates validate <NAME>
FLAGS:
ARGS:
<NAME>    Template name
(Ricks-MacBook-Pro):~/cloudtruth-cli
```
Here's a sample failure (from the CLI integration tests):
````
/Users/rick/cloudtruth-cli/target/debug/cloudtruth --project proj-int-broken template validate "temp-int-broken"
Error: 
0: Evaluation failed:
param2: The external content of `github://rickporter-tuono/hello-world/master/README.md` is not present.
Location: …
```

Add 'template validate' command

---

CHANGELOG.md
Cargo.lock
Cargo.toml
tests/help.txt

* Enhanced `parameters set` to allow parameter creation without a value for any environment.
* Added `template validate` to check if an existing template still works.
* Fixed `parameters environment --as-of` issue when using a tag name.
* Added `configuration profile` commands to avoid need to modify configuration file with editor.
* Move `configuration list` functionality into `configuration profile list`.
* Improved handling for many error responses to provide more understandable information.

1.0.9 release

---

CHANGELOG.md
Cargo.lock
Cargo.toml
tests/help.txt

* Added `--as-of` to `templates get` for raw or evaluated template at specified date/time (or tag).
* Changes to `configuration profile set`:
* Fixed issue with reporting wrong action.
* Added ability to set a source-profile using `--source`.
* Improved error handling to provide more understandable information.
* Updated several help strings.

1.0.10 release

---

CHANGELOG.md
Cargo.lock
Cargo.toml
tests/help.txt

* Added several `integrations` commands:
* Added `refresh` to trigger update of an integration connection status.
* Added `get` to get detailed information about an integration.
* Added `pushes <set|delete|list|get|sync|tasks>` commands to manage push actions.
* Added `schema` command to get the latest schema from the server, or local CLI version.
* Added `--user`, `--before`, and `--after` filters to `audit-logs list`.
* Fixed issue with `templates history --as-of` using tags.
* Show values for items when a `--format <table|csv|json|yaml>` is specified.

1.0.13 release

---

CHANGELOG.md
Cargo.lock
Cargo.toml
tests/help.txt

* BREAKING CHANGE:
* Moved `integrations pushes` commands to `actions pushes`.
* Made integration-name optional (using `--integration|-i <name>`) for most `pushes` commands.
* Internal changes to improve testing.

1.1.0 release

---

client/src/apis/api_api.rs
openapi.json
patch_client.py
src/cli.rs
src/database/api.rs
src/database/api_error.rs
src/schema.rs
tests/help.txt
tests/pytest/test_misc.py

1. Add `schema diff` command
2. Return same schema each time
* Pass through server response (yaml, or json) instead of processing to local version
* Include openapi.json file to give local json formatted output

Several schema command improvements

---

.github/workflows/dev.yaml
tests/pytest/test_actions.py

We were not waiting for the "tag update" to take effect before checking that the "push update" had completed. This meant that sometimes the "tag update" masked that the "push update" had not finished.

Fix test_action_complete()

---

src/cli.rs
src/run.rs
src/subprocess.rs
tests/pytest/test_run.py

Adds `--strict` flag to cloudtruth run command.
Returns an error if any cloudtruth parameter is unset. 
This PR uses client side logic, checking to see if a value is "-" (this is the closest equivalent for null)

add strict arg to run command

---

tests/help.txt

help.txt was out of sync with latest release version and the new --strict flag

regenerate test help.txt used in precommit script

---

tests/pytest/cleanup.py
tests/pytest/test_integrations.py
tests/pytest/test_parameters.py
tests/pytest/test_templates.py

Most changes are related to templates becoming secret when referencing secret parameters
other fixes:
* error message changed when a missing reference is found in a template
* fixed TypeError bug in the test cleanup script
* made some of the test environments easier to cleanup by giving them prefixes
* small fix to param diff test in case when comparing same env at two identical timestamps

update broken integration tests related to secrets in templates (and other small fixes; see description)

---

src/config/env.rs
src/config/file.rs
src/config/mod.rs
src/config/profiles.rs
src/database/openapi.rs
tests/pytest/test_configuration.py

Adds `CLOUDTRUTH_ACCEPT_INVALID_CERTS` environment variable and yaml config key `accept_invalid_certs` to trust any credentials from the server

add config option to accept invalid certs

---

.github/workflows/ci.yml
src/config/mod.rs
tests/pytest/cleanup.py
tests/pytest/test_actions.py
tests/pytest/test_args.py
tests/pytest/test_audit_log.py
tests/pytest/test_backup.py
tests/pytest/test_environments.py
tests/pytest/test_groups.py
tests/pytest/test_import.py
tests/pytest/test_integrations.py
tests/pytest/test_parameters.py
tests/pytest/test_projects.py
tests/pytest/test_templates.py
tests/pytest/test_timing.py
tests/pytest/test_types.py
tests/pytest/test_users.py
tests/pytest/testcase.py

* Bumping the default request timeout from 30 seconds to 90 seconds. this more closely matches the server-side timeout value
* Added a standard prefix for all names created in test data. Now all `make_name` calls add a `testcli` prefix to the generated names. This makes it easier to run the cleanup script against test data
* Added the new group CLI commands to cleanup and teardown actions in the test suite
Additionally, I've manually wiped most of the old CI test data on the staging environment. The environment was very bloated with lingering test data and causing some tests to timeout from too much data (mainly backup and import tests)

Refactoring to improve stability/usability of integration test suite

---

.github/workflows/ci.yml
.github/workflows/dev.yaml
.github/workflows/nightly.yaml
.github/workflows/production.yml
.github/workflows/staging.yml

this should prevent data collisions from re-running test workflows

add attempt number to job ID of CI tests

---

.github/workflows/check-pre-release.yml
.github/workflows/ci.yml
.github/workflows/create-draft-release.yml
.github/workflows/dev.yaml
.github/workflows/nightly.yaml
.github/workflows/production.yml
.github/workflows/staging.yml

Node 12 deprecation action updates
still to do......
actions-rs/toolchain waiting on fix
nightly still will fail
mac error that I'll have to look into

Workflow actions updates part 1

---

Cargo.lock
Cargo.toml
integration-tests/test_parameters.py
integration-tests/test_templates.py
integration-tests/testcase.py
src/config/file.rs
src/config/update.rs
src/database/templates.rs
src/main.rs
src/utils.rs

the old format for `--as-of` option no longer works with the latest server API, so this changes the formatting to match what the server currently accepts.
also updated `chrono` dependency to clean up some of the datetime logic, fixed a few tests related to the issue, and fixed deprecation warnings from chrono

fix issue with datetime format incompatibility with latest API server

---

Cargo.lock
Cargo.toml

Issue began after updating compiler to 1.67
see phsym/prettytable-rs#145

update prettytable version to fix segfault when using csv output

---

client/src/models/aws_integration.rs
client/src/models/features_response.rs
integration-tests/test_templates.py
openapi.json
openapi.yml
src/database/template_history.rs
src/database/templates.rs
src/templates.rs

This was temporarily removed but is now re-implemented. Field names have changed from `history_date` and `history_user` to `modified_at` and `modified_by` respectively. Also the user field has changed from being an ID to being either an email address for users or `Service Account (<NAME>)` for service accounts.

restore template history date and user

---

CHANGELOG.md
Cargo.lock
Cargo.toml
build/help.txt
build/templates/test-release/workflow-header.yaml

also fixes a leftover typo in one of the workflow templates. the fix was already in the workflow, but the template was not updated.

update Cargo.toml and CHANGELOG for 1.2.0 release

---

.github/workflows/ci.yml
.github/workflows/nightly.yaml
.github/workflows/production.yml
.github/workflows/staging.yml
integration-tests/live_test.py

Tracks additional test data information, and reports the test information based on presence of `-r|--reports` flag.
The test reports could be generalized to create XML files, but currently just put the data directly in the logs as text. This allows for tracking all test durations.

Add extra test info to integration tests

---

integration-tests/live_test.py
integration-tests/testcase.py

debug logging output was causing test cases to fail on some assertions. this adds code to the test harness to hide debug lines from the test cases so that they continue to pass but the debug lines still get output to console.
this makes it possible to use the integration test runs to generate performance and profiling metrics

add ability for test cases to pass with REST debug logging enabled

---

.github/workflows/build-release.yml
.github/workflows/build.yml
.github/workflows/check-pre-release.yml
.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/nightly.yml
.github/workflows/test-nightly.yml
.github/workflows/test-production.yml
.github/workflows/test-release.yml
.github/workflows/test-staging.yml

tests that run off of the nightly and staging releases do not have debug information, so logging backtraces by default is not useful and spams the test reports.
this change adds an input to the `test-staging` workflow to enable/disable backtraces, which is by default disabled. the CI tests enable this option to continue showing backtrace information.

allow RUST_BACKTRACE to be configurable in CI tests

---

crates/integration-test-harness/src/data/environment.rs
crates/integration-test-harness/src/data/name.rs
crates/integration-test-harness/src/data/project.rs
crates/integration-test-harness/src/data/resource.rs
crates/integration-test-harness/src/data/scope.rs

test harness improvement in preparation for templates, which can be a TestResource but can't be constructed from only a name (they need a body as well)

move from_name method from TestResource to NameConstructors

---

tests/pytest/README.md
tests/pytest/live_test.py
tests/pytest/test_backup.py
tests/pytest/test_integrations.py
tests/pytest/test_timing.py
tests/pytest/testcase.py
tests/test_integrations.rs

Currently these are the remaining Python integration tests:
* `test_integrations.py`
* `test_backup.py` (currently unused due to performance bugs)
* `test_timings.py` (should be rewritten as Rust benchmark in future)
test_integrations.py has been incorporated into the Rust test suite via spawning a child Python process. In the future this should be ported over or the test design for integrations should be changed, as it makes special assumptions about the CloudTruth project in order to function.

copy remaining python tests into Rust integration tests

---

.github/workflows/test-production.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
crates/cloudtruth-config/Cargo.toml
crates/cloudtruth-installer/Cargo.toml
examples/help-text/cloudtruth.md
src/database/parameter_details.rs
src/parameters.rs
tests/harness/Cargo.toml
tests/macros/Cargo.toml

I thought I could get away with the simpler fix. Turns out that didn't cover all cases

fix updating values of overridden parameters
